[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yutouni", email = "1347673374@qq.com" }
]
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.18.5",
    "boto3>=1.40.0",
    "fastapi>=0.141.1",
    "openpyxl>=3.1.5",
    "pymysql>=1.2.0",
    "python-multipart>=0.0.20",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.51",
    "uvicorn>=0.52.1",
]

[tool.uv]
package = false
